// flow-typed signature: 4d8959dc734ced07d3a015c05437c5d7
// flow-typed version: <<STUB>>/parsimmon_v1.12.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parsimmon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parsimmon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parsimmon/build/parsimmon.umd.min' {
  declare module.exports: any;
}

declare module 'parsimmon/src/parsimmon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parsimmon/build/parsimmon.umd.min.js' {
  declare module.exports: $Exports<'parsimmon/build/parsimmon.umd.min'>;
}
declare module 'parsimmon/src/parsimmon.js' {
  declare module.exports: $Exports<'parsimmon/src/parsimmon'>;
}
