name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versiodn: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"
        node-versiosdn: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
